// <auto-generated />
using System;
using Maia.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MaiaDbContext))]
    [Migration("20260429152137_MoveSourceTableToScanCheckRule")]
    partial class MoveSourceTableToScanCheckRule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Maia.Core.Entities.AiRecommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<bool>("AutoFixAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ErrorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailureId")
                        .HasColumnType("int");

                    b.Property<string>("FixCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsExecuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("OperatorApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RecommendedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SuggestedAction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("RecommendationId");

                    b.HasIndex("ErrorTypeId");

                    b.HasIndex("FailureId");

                    b.ToTable("AIRecommendations", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("AuditId");

                    b.HasIndex("FailureId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ClassificationRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ErrorTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("RuleId");

                    b.HasIndex("ErrorTypeId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("ClassificationRules", (string)null);

                    b.HasData(
                        new
                        {
                            RuleId = 1,
                            Confidence = 0.95m,
                            ErrorTypeId = 1,
                            IsActive = true,
                            JobTypeId = 1,
                            Pattern = "FileNotFoundException",
                            Priority = 1
                        },
                        new
                        {
                            RuleId = 2,
                            Confidence = 0.85m,
                            ErrorTypeId = 4,
                            IsActive = true,
                            JobTypeId = 1,
                            Pattern = "DTS_E_OLEDBERROR",
                            Priority = 2
                        },
                        new
                        {
                            RuleId = 3,
                            Confidence = 0.93m,
                            ErrorTypeId = 2,
                            IsActive = true,
                            JobTypeId = 1,
                            Pattern = "DTS_E_CANNOTACQUIRECONNECTION",
                            Priority = 3
                        },
                        new
                        {
                            RuleId = 4,
                            Confidence = 0.88m,
                            ErrorTypeId = 3,
                            IsActive = true,
                            JobTypeId = 1,
                            Pattern = "Timeout expired",
                            Priority = 4
                        },
                        new
                        {
                            RuleId = 5,
                            Confidence = 0.95m,
                            ErrorTypeId = 2,
                            IsActive = true,
                            JobTypeId = 2,
                            Pattern = "Login failed",
                            Priority = 1
                        },
                        new
                        {
                            RuleId = 6,
                            Confidence = 0.95m,
                            ErrorTypeId = 1,
                            IsActive = true,
                            JobTypeId = 3,
                            Pattern = "FileNotFoundError",
                            Priority = 1
                        },
                        new
                        {
                            RuleId = 7,
                            Confidence = 0.90m,
                            ErrorTypeId = 2,
                            IsActive = true,
                            JobTypeId = 3,
                            Pattern = "ConnectionRefusedError",
                            Priority = 2
                        },
                        new
                        {
                            RuleId = 8,
                            Confidence = 0.88m,
                            ErrorTypeId = 5,
                            IsActive = true,
                            JobTypeId = 4,
                            Pattern = "Access is denied",
                            Priority = 1
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.ErrorType", b =>
                {
                    b.Property<int>("ErrorTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ErrorTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ErrorTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ErrorTypeId = 1,
                            Code = "FileNotFound",
                            DisplayName = "File Not Found",
                            IsActive = true,
                            Severity = "High"
                        },
                        new
                        {
                            ErrorTypeId = 2,
                            Code = "DbConnection",
                            DisplayName = "Database Connection Error",
                            IsActive = true,
                            Severity = "High"
                        },
                        new
                        {
                            ErrorTypeId = 3,
                            Code = "Timeout",
                            DisplayName = "Execution Timeout",
                            IsActive = true,
                            Severity = "Medium"
                        },
                        new
                        {
                            ErrorTypeId = 4,
                            Code = "Transform",
                            DisplayName = "Data Transform Failure",
                            IsActive = true,
                            Severity = "Medium"
                        },
                        new
                        {
                            ErrorTypeId = 5,
                            Code = "Permission",
                            DisplayName = "Access Denied",
                            IsActive = true,
                            Severity = "High"
                        },
                        new
                        {
                            ErrorTypeId = 6,
                            Code = "Unknown",
                            DisplayName = "Unknown Error",
                            IsActive = true,
                            Severity = "Low"
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.FixExecutionLog", b =>
                {
                    b.Property<int>("FixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FixId"));

                    b.Property<string>("ExecutedAction")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ExecutedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailureId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("ResultDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FixId");

                    b.HasIndex("FailureId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("FixExecutionLog", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.FixPolicyRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<string>("ActionPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActionTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ActionToApply")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ErrorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FixCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAutoHealEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.HasKey("RuleId");

                    b.HasIndex("ErrorTypeId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("FixPolicyRules", (string)null);

                    b.HasData(
                        new
                        {
                            RuleId = 1,
                            ActionPayload = "http://jobs.internal/api/jobs/{failureId}/retry",
                            ActionTimestamp = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActionToApply = "Retry DTSX job via job-management API",
                            ActionType = "ApiCall",
                            CreatedBy = "System",
                            Enabled = true,
                            ErrorTypeId = 3,
                            FixCategory = "Retry",
                            IsAutoHealEligible = true,
                            JobTypeId = 1
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.JobFailure", b =>
                {
                    b.Property<int>("FailureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FailureId"));

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ErrorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<string>("SourceLogPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StepName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FailureId");

                    b.HasIndex("ErrorTypeId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("MonitoredJobId");

                    b.ToTable("JobFailures", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.JobType", b =>
                {
                    b.Property<int>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes", (string)null);

                    b.HasData(
                        new
                        {
                            JobTypeId = 1,
                            Description = "SQL Server Integration Services package",
                            IsActive = true,
                            Name = "DTSX"
                        },
                        new
                        {
                            JobTypeId = 2,
                            Description = "SQL Server Agent Job",
                            IsActive = true,
                            Name = "SqlAgent"
                        },
                        new
                        {
                            JobTypeId = 3,
                            Description = "Python script",
                            IsActive = true,
                            Name = "Python"
                        },
                        new
                        {
                            JobTypeId = 4,
                            Description = "PowerShell script",
                            IsActive = true,
                            Name = "PowerShell"
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJob", b =>
                {
                    b.Property<int>("MonitoredJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonitoredJobId"));

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<string>("LogFolder")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogSourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PollingIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(300);

                    b.Property<int>("ScanTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SearchPatterns")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MonitoredJobId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ScanTypeId");

                    b.ToTable("MonitoredJobs", (string)null);

                    b.HasData(
                        new
                        {
                            MonitoredJobId = 1,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "עיבוד ניודים נכנסים",
                            DisplayName = "Trap Interfaces",
                            IsActive = true,
                            JobTypeId = 1,
                            LogFolder = "c:\\logs",
                            Name = "TrapInterfaces",
                            PollingIntervalSeconds = 300,
                            ScanTypeId = 1,
                            SearchPatterns = "Trap*.log"
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJobRule", b =>
                {
                    b.Property<int>("JobRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobRuleId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.HasKey("JobRuleId");

                    b.HasIndex("RuleId");

                    b.HasIndex("MonitoredJobId", "RuleId")
                        .IsUnique();

                    b.ToTable("MonitoredJobRules", (string)null);

                    b.HasData(
                        new
                        {
                            JobRuleId = 1,
                            IsActive = true,
                            MonitoredJobId = 1,
                            RuleId = 4
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.OperatorAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ActionTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.HasKey("ActionId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("OperatorActions", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanCheckRule", b =>
                {
                    b.Property<int>("CheckRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckRuleId"));

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExpectedValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceTable")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CheckRuleId");

                    b.HasIndex("MonitoredJobId");

                    b.ToTable("ScanCheckRules", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanTypeDefinition", b =>
                {
                    b.Property<int>("ScanTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScanTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ScanTypeId");

                    b.ToTable("ScanTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ScanTypeId = 1,
                            Description = "Scan log files in a folder matching glob patterns",
                            Name = "FileSystem"
                        },
                        new
                        {
                            ScanTypeId = 2,
                            Description = "Query a SQL table and check column values against rules",
                            Name = "Database"
                        },
                        new
                        {
                            ScanTypeId = 3,
                            Description = "Poll an HTTP endpoint and inspect the response",
                            Name = "ApiEndpoint"
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.AiRecommendation", b =>
                {
                    b.HasOne("Maia.Core.Entities.ErrorType", "ErrorType")
                        .WithMany("Recommendations")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.JobFailure", "Failure")
                        .WithMany("Recommendations")
                        .HasForeignKey("FailureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErrorType");

                    b.Navigation("Failure");
                });

            modelBuilder.Entity("Maia.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("Maia.Core.Entities.JobFailure", "Failure")
                        .WithMany("AuditLogs")
                        .HasForeignKey("FailureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Failure");
                });

            modelBuilder.Entity("Maia.Core.Entities.ClassificationRule", b =>
                {
                    b.HasOne("Maia.Core.Entities.ErrorType", "ErrorType")
                        .WithMany("ClassificationRules")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.JobType", "JobType")
                        .WithMany("ClassificationRules")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ErrorType");

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("Maia.Core.Entities.FixExecutionLog", b =>
                {
                    b.HasOne("Maia.Core.Entities.JobFailure", "Failure")
                        .WithMany("FixExecutionLogs")
                        .HasForeignKey("FailureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.AiRecommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Failure");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Maia.Core.Entities.FixPolicyRule", b =>
                {
                    b.HasOne("Maia.Core.Entities.ErrorType", "ErrorType")
                        .WithMany("FixPolicyRules")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.JobType", "JobType")
                        .WithMany("FixPolicyRules")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ErrorType");

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("Maia.Core.Entities.JobFailure", b =>
                {
                    b.HasOne("Maia.Core.Entities.ErrorType", "ErrorType")
                        .WithMany("JobFailures")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maia.Core.Entities.JobType", "JobType")
                        .WithMany("JobFailures")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany("Failures")
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ErrorType");

                    b.Navigation("JobType");

                    b.Navigation("MonitoredJob");
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJob", b =>
                {
                    b.HasOne("Maia.Core.Entities.JobType", "JobType")
                        .WithMany("MonitoredJobs")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.ScanTypeDefinition", "ScanTypeDefinition")
                        .WithMany("MonitoredJobs")
                        .HasForeignKey("ScanTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobType");

                    b.Navigation("ScanTypeDefinition");
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJobRule", b =>
                {
                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany("JobRules")
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.ClassificationRule", "Rule")
                        .WithMany("MonitoredJobRules")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonitoredJob");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Maia.Core.Entities.OperatorAction", b =>
                {
                    b.HasOne("Maia.Core.Entities.AiRecommendation", "Recommendation")
                        .WithMany("OperatorActions")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanCheckRule", b =>
                {
                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany("ScanCheckRules")
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredJob");
                });

            modelBuilder.Entity("Maia.Core.Entities.AiRecommendation", b =>
                {
                    b.Navigation("OperatorActions");
                });

            modelBuilder.Entity("Maia.Core.Entities.ClassificationRule", b =>
                {
                    b.Navigation("MonitoredJobRules");
                });

            modelBuilder.Entity("Maia.Core.Entities.ErrorType", b =>
                {
                    b.Navigation("ClassificationRules");

                    b.Navigation("FixPolicyRules");

                    b.Navigation("JobFailures");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Maia.Core.Entities.JobFailure", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("FixExecutionLogs");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Maia.Core.Entities.JobType", b =>
                {
                    b.Navigation("ClassificationRules");

                    b.Navigation("FixPolicyRules");

                    b.Navigation("JobFailures");

                    b.Navigation("MonitoredJobs");
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJob", b =>
                {
                    b.Navigation("Failures");

                    b.Navigation("JobRules");

                    b.Navigation("ScanCheckRules");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanTypeDefinition", b =>
                {
                    b.Navigation("MonitoredJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
