// <auto-generated />
using System;
using Maia.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MaiaDbContext))]
    [Migration("20260609193221_AddScanSourceEntity")]
    partial class AddScanSourceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Maia.Core.Entities.AiRecommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<bool>("AutoFixAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ErrorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailureId")
                        .HasColumnType("int");

                    b.Property<string>("FixCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsExecuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("OperatorApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RecommendedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SuggestedAction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("RecommendationId");

                    b.HasIndex("ErrorTypeId");

                    b.HasIndex("FailureId");

                    b.HasIndex("IsExecuted", "ClaimedAt")
                        .HasDatabaseName("IX_AIRecommendations_ClaimEligible")
                        .HasFilter("[IsExecuted] = 0");

                    b.ToTable("AIRecommendations", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FailureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("AuditId");

                    b.HasIndex("FailureId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ClassificationRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ErrorTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SuggestedConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SuggestedFromHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("RuleId");

                    b.HasIndex("ErrorTypeId");

                    b.HasIndex("JobTypeId", "Pattern")
                        .IsUnique()
                        .HasDatabaseName("UX_ClassificationRules_ActiveKey")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ClassificationRules", (string)null);

                    b.HasData(
                        new
                        {
                            RuleId = 1,
                            Confidence = 0.95m,
                            ErrorTypeId = 1,
                            IsActive = true,
                            JobTypeId = 1,
                            Pattern = "FileNotFoundException",
                            Priority = 1
                        },
                        new
                        {
                            RuleId = 2,
                            Confidence = 0.85m,
                            ErrorTypeId = 4,
                            IsActive = true,
                            JobTypeId = 1,
                            Pattern = "DTS_E_OLEDBERROR",
                            Priority = 2
                        },
                        new
                        {
                            RuleId = 3,
                            Confidence = 0.93m,
                            ErrorTypeId = 2,
                            IsActive = true,
                            JobTypeId = 1,
                            Pattern = "DTS_E_CANNOTACQUIRECONNECTION",
                            Priority = 3
                        },
                        new
                        {
                            RuleId = 4,
                            Confidence = 0.88m,
                            ErrorTypeId = 3,
                            IsActive = true,
                            JobTypeId = 1,
                            Pattern = "Timeout expired",
                            Priority = 4
                        },
                        new
                        {
                            RuleId = 5,
                            Confidence = 0.95m,
                            ErrorTypeId = 2,
                            IsActive = true,
                            JobTypeId = 2,
                            Pattern = "Login failed",
                            Priority = 1
                        },
                        new
                        {
                            RuleId = 6,
                            Confidence = 0.95m,
                            ErrorTypeId = 1,
                            IsActive = true,
                            JobTypeId = 3,
                            Pattern = "FileNotFoundError",
                            Priority = 1
                        },
                        new
                        {
                            RuleId = 7,
                            Confidence = 0.90m,
                            ErrorTypeId = 2,
                            IsActive = true,
                            JobTypeId = 3,
                            Pattern = "ConnectionRefusedError",
                            Priority = 2
                        },
                        new
                        {
                            RuleId = 8,
                            Confidence = 0.88m,
                            ErrorTypeId = 5,
                            IsActive = true,
                            JobTypeId = 4,
                            Pattern = "Access is denied",
                            Priority = 1
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.ErrorType", b =>
                {
                    b.Property<int>("ErrorTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ErrorTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ErrorTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ErrorTypeId = 1,
                            Code = "FileNotFound",
                            DisplayName = "File Not Found",
                            IsActive = true,
                            Severity = "High"
                        },
                        new
                        {
                            ErrorTypeId = 2,
                            Code = "DbConnection",
                            DisplayName = "Database Connection Error",
                            IsActive = true,
                            Severity = "High"
                        },
                        new
                        {
                            ErrorTypeId = 3,
                            Code = "Timeout",
                            DisplayName = "Execution Timeout",
                            IsActive = true,
                            Severity = "Medium"
                        },
                        new
                        {
                            ErrorTypeId = 4,
                            Code = "Transform",
                            DisplayName = "Data Transform Failure",
                            IsActive = true,
                            Severity = "Medium"
                        },
                        new
                        {
                            ErrorTypeId = 5,
                            Code = "Permission",
                            DisplayName = "Access Denied",
                            IsActive = true,
                            Severity = "High"
                        },
                        new
                        {
                            ErrorTypeId = 6,
                            Code = "Unknown",
                            DisplayName = "Unknown Error",
                            IsActive = true,
                            Severity = "Low"
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.FixExecutionLog", b =>
                {
                    b.Property<int>("FixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FixId"));

                    b.Property<string>("ExecutedAction")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ExecutedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailureId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("ResultDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FixId");

                    b.HasIndex("FailureId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("FixExecutionLog", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.FixPolicyRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<string>("ActionPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActionTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ActionToApply")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ErrorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FixCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAutoHealEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SuggestedConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SuggestedFromHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("RuleId");

                    b.HasIndex("ErrorTypeId");

                    b.HasIndex("JobTypeId", "ErrorTypeId")
                        .IsUnique()
                        .HasDatabaseName("UX_FixPolicyRules_DefaultActiveKey")
                        .HasFilter("[Enabled] = 1 AND [MonitoredJobId] IS NULL");

                    b.HasIndex("MonitoredJobId", "ErrorTypeId")
                        .IsUnique()
                        .HasDatabaseName("UX_FixPolicyRules_OverrideActiveKey")
                        .HasFilter("[Enabled] = 1 AND [MonitoredJobId] IS NOT NULL");

                    b.ToTable("FixPolicyRules", (string)null);

                    b.HasData(
                        new
                        {
                            RuleId = 1,
                            ActionPayload = "http://jobs.internal/api/jobs/{failureId}/retry",
                            ActionTimestamp = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActionToApply = "Retry DTSX job via job-management API",
                            ActionType = "ApiCall",
                            CreatedBy = "System",
                            Enabled = true,
                            ErrorTypeId = 3,
                            FixCategory = "Retry",
                            IsAutoHealEligible = true,
                            JobTypeId = 1
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.FixPolicyRuleStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepId"));

                    b.Property<string>("ActionPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("StepId");

                    b.HasIndex("RuleId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_FixPolicyRuleSteps_RuleId_StepOrder");

                    b.ToTable("FixPolicyRuleSteps", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.JobFailure", b =>
                {
                    b.Property<int>("FailureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FailureId"));

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ErrorTypeId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<int?>("ScanSourceId")
                        .HasColumnType("int");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceLogPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StepName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FailureId");

                    b.HasIndex("ErrorTypeId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("MonitoredJobId");

                    b.HasIndex("ScanSourceId");

                    b.ToTable("JobFailures", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.JobType", b =>
                {
                    b.Property<int>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes", (string)null);

                    b.HasData(
                        new
                        {
                            JobTypeId = 1,
                            Description = "SQL Server Integration Services package",
                            IsActive = true,
                            Name = "DTSX"
                        },
                        new
                        {
                            JobTypeId = 2,
                            Description = "SQL Server Agent Job",
                            IsActive = true,
                            Name = "SqlAgent"
                        },
                        new
                        {
                            JobTypeId = 3,
                            Description = "Python script",
                            IsActive = true,
                            Name = "Python"
                        },
                        new
                        {
                            JobTypeId = 4,
                            Description = "PowerShell script",
                            IsActive = true,
                            Name = "PowerShell"
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJob", b =>
                {
                    b.Property<int>("MonitoredJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonitoredJobId"));

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IncludeSubfolders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("InputFolder")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<string>("LogFolder")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogSourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PollingIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(300);

                    b.Property<int>("ScanTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SearchPatterns")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MonitoredJobId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ScanTypeId");

                    b.ToTable("MonitoredJobs", (string)null);

                    b.HasData(
                        new
                        {
                            MonitoredJobId = 1,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "עיבוד ניודים נכנסים",
                            DisplayName = "Trap Interfaces",
                            IncludeSubfolders = false,
                            IsActive = true,
                            JobTypeId = 1,
                            LogFolder = "c:\\logs",
                            Name = "TrapInterfaces",
                            PollingIntervalSeconds = 300,
                            ScanTypeId = 1,
                            SearchPatterns = "Trap*.log"
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJobLease", b =>
                {
                    b.Property<int>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastRunCompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastRunError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LastRunOutcome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastRunStartedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LeasedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LeasedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LeasedUntil")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NextEligibleAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("'0001-01-01'");

                    b.HasKey("MonitoredJobId");

                    b.HasIndex("NextEligibleAt", "LeasedUntil")
                        .HasDatabaseName("IX_MonitoredJobLeases_Eligible");

                    b.ToTable("MonitoredJobLeases", (string)null);

                    b.HasData(
                        new
                        {
                            MonitoredJobId = 1,
                            NextEligibleAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJobRule", b =>
                {
                    b.Property<int>("JobRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobRuleId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.HasKey("JobRuleId");

                    b.HasIndex("RuleId");

                    b.HasIndex("MonitoredJobId", "RuleId")
                        .IsUnique();

                    b.ToTable("MonitoredJobRules", (string)null);

                    b.HasData(
                        new
                        {
                            JobRuleId = 1,
                            IsActive = true,
                            MonitoredJobId = 1,
                            RuleId = 4
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.OperatorAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ActionTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.HasKey("ActionId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("OperatorActions", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanCheckRule", b =>
                {
                    b.Property<int>("CheckRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckRuleId"));

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExpectedValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExtractorLocator")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExtractorPredicateType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExtractorPredicateValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExtractorType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilePathColumn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentifierLocator")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InputPathPattern")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<int?>("ScanSourceId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceIdColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceTable")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WatermarkColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CheckRuleId");

                    b.HasIndex("MonitoredJobId");

                    b.HasIndex("ScanSourceId");

                    b.ToTable("ScanCheckRules", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanContentWatermark", b =>
                {
                    b.Property<int>("WatermarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatermarkId"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<int?>("ScanSourceId")
                        .HasColumnType("int");

                    b.HasKey("WatermarkId");

                    b.HasIndex("ScanSourceId");

                    b.HasIndex("MonitoredJobId", "FilePath")
                        .IsUnique();

                    b.ToTable("ScanContentWatermarks", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanDbWatermark", b =>
                {
                    b.Property<int>("WatermarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatermarkId"));

                    b.Property<int>("CheckRuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("WatermarkValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WatermarkId");

                    b.HasIndex("CheckRuleId")
                        .IsUnique();

                    b.ToTable("ScanDbWatermarks", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanFileWatermark", b =>
                {
                    b.Property<int>("WatermarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatermarkId"));

                    b.Property<long>("ByteOffset")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<int?>("ScanSourceId")
                        .HasColumnType("int");

                    b.HasKey("WatermarkId");

                    b.HasIndex("ScanSourceId");

                    b.HasIndex("MonitoredJobId", "FilePath")
                        .IsUnique();

                    b.ToTable("ScanFileWatermarks", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanRunHistory", b =>
                {
                    b.Property<int>("ScanRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScanRunId"));

                    b.Property<int>("Classifications")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FailuresDetected")
                        .HasColumnType("int");

                    b.Property<int>("IdentifierExtractionFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("LeasedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OversizeFileSkips")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PredicateUnevaluableSkips")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Recommendations")
                        .HasColumnType("int");

                    b.Property<int?>("ScanSourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("ScanRunId");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_ScanRunHistory_Failures")
                        .HasFilter("[Outcome] <> 'Success'");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StartedAt"), new[] { "MonitoredJobId", "Outcome", "Error" });

                    b.HasIndex("MonitoredJobId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ScanRunHistory_Job_StartedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("MonitoredJobId", "StartedAt"), new[] { "CompletedAt", "DurationMs", "Outcome", "FailuresDetected", "Classifications", "Recommendations" });

                    b.HasIndex("ScanSourceId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ScanRunHistory_Source_StartedAt");

                    b.ToTable("ScanRunHistory", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanSource", b =>
                {
                    b.Property<int>("ScanSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScanSourceId"));

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IncludeSubfolders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("InputFolder")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogFolder")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogSourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MonitoredJobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PollingIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(300);

                    b.Property<int>("ScanTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SearchPatterns")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ScanSourceId");

                    b.HasIndex("MonitoredJobId")
                        .HasDatabaseName("IX_ScanSources_MonitoredJobId");

                    b.HasIndex("ScanTypeId");

                    b.ToTable("ScanSources", (string)null);
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanTypeDefinition", b =>
                {
                    b.Property<int>("ScanTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScanTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LeaseDurationSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(300);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ScanTypeId");

                    b.ToTable("ScanTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ScanTypeId = 1,
                            Description = "Scan log files in a folder matching glob patterns",
                            LeaseDurationSeconds = 300,
                            Name = "FileSystem"
                        },
                        new
                        {
                            ScanTypeId = 2,
                            Description = "Query a SQL table and check column values against rules",
                            LeaseDurationSeconds = 1800,
                            Name = "Database"
                        },
                        new
                        {
                            ScanTypeId = 3,
                            Description = "Poll an HTTP endpoint and inspect the response",
                            LeaseDurationSeconds = 60,
                            Name = "ApiEndpoint"
                        },
                        new
                        {
                            ScanTypeId = 4,
                            Description = "Structured extraction from input data files (XML, …)",
                            LeaseDurationSeconds = 300,
                            Name = "FileContent"
                        });
                });

            modelBuilder.Entity("Maia.Core.Entities.AiRecommendation", b =>
                {
                    b.HasOne("Maia.Core.Entities.ErrorType", "ErrorType")
                        .WithMany("Recommendations")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.JobFailure", "Failure")
                        .WithMany("Recommendations")
                        .HasForeignKey("FailureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErrorType");

                    b.Navigation("Failure");
                });

            modelBuilder.Entity("Maia.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("Maia.Core.Entities.JobFailure", "Failure")
                        .WithMany("AuditLogs")
                        .HasForeignKey("FailureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Failure");
                });

            modelBuilder.Entity("Maia.Core.Entities.ClassificationRule", b =>
                {
                    b.HasOne("Maia.Core.Entities.ErrorType", "ErrorType")
                        .WithMany("ClassificationRules")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.JobType", "JobType")
                        .WithMany("ClassificationRules")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ErrorType");

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("Maia.Core.Entities.FixExecutionLog", b =>
                {
                    b.HasOne("Maia.Core.Entities.JobFailure", "Failure")
                        .WithMany("FixExecutionLogs")
                        .HasForeignKey("FailureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.AiRecommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Failure");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Maia.Core.Entities.FixPolicyRule", b =>
                {
                    b.HasOne("Maia.Core.Entities.ErrorType", "ErrorType")
                        .WithMany("FixPolicyRules")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.JobType", "JobType")
                        .WithMany("FixPolicyRules")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany()
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ErrorType");

                    b.Navigation("JobType");

                    b.Navigation("MonitoredJob");
                });

            modelBuilder.Entity("Maia.Core.Entities.FixPolicyRuleStep", b =>
                {
                    b.HasOne("Maia.Core.Entities.FixPolicyRule", "Rule")
                        .WithMany("Steps")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Maia.Core.Entities.JobFailure", b =>
                {
                    b.HasOne("Maia.Core.Entities.ErrorType", "ErrorType")
                        .WithMany("JobFailures")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maia.Core.Entities.JobType", "JobType")
                        .WithMany("JobFailures")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany("Failures")
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Maia.Core.Entities.ScanSource", "ScanSource")
                        .WithMany()
                        .HasForeignKey("ScanSourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ErrorType");

                    b.Navigation("JobType");

                    b.Navigation("MonitoredJob");

                    b.Navigation("ScanSource");
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJob", b =>
                {
                    b.HasOne("Maia.Core.Entities.JobType", "JobType")
                        .WithMany("MonitoredJobs")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.ScanTypeDefinition", "ScanTypeDefinition")
                        .WithMany("MonitoredJobs")
                        .HasForeignKey("ScanTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobType");

                    b.Navigation("ScanTypeDefinition");
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJobLease", b =>
                {
                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithOne("Lease")
                        .HasForeignKey("Maia.Core.Entities.MonitoredJobLease", "MonitoredJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredJob");
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJobRule", b =>
                {
                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany("JobRules")
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.ClassificationRule", "Rule")
                        .WithMany("MonitoredJobRules")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonitoredJob");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Maia.Core.Entities.OperatorAction", b =>
                {
                    b.HasOne("Maia.Core.Entities.AiRecommendation", "Recommendation")
                        .WithMany("OperatorActions")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanCheckRule", b =>
                {
                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany("ScanCheckRules")
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.ScanSource", "ScanSource")
                        .WithMany("ScanCheckRules")
                        .HasForeignKey("ScanSourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MonitoredJob");

                    b.Navigation("ScanSource");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanContentWatermark", b =>
                {
                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany()
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.ScanSource", "ScanSource")
                        .WithMany()
                        .HasForeignKey("ScanSourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MonitoredJob");

                    b.Navigation("ScanSource");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanDbWatermark", b =>
                {
                    b.HasOne("Maia.Core.Entities.ScanCheckRule", "CheckRule")
                        .WithMany()
                        .HasForeignKey("CheckRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckRule");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanFileWatermark", b =>
                {
                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany()
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.ScanSource", "ScanSource")
                        .WithMany()
                        .HasForeignKey("ScanSourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MonitoredJob");

                    b.Navigation("ScanSource");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanRunHistory", b =>
                {
                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany()
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.ScanSource", "ScanSource")
                        .WithMany()
                        .HasForeignKey("ScanSourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MonitoredJob");

                    b.Navigation("ScanSource");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanSource", b =>
                {
                    b.HasOne("Maia.Core.Entities.MonitoredJob", "MonitoredJob")
                        .WithMany("ScanSources")
                        .HasForeignKey("MonitoredJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maia.Core.Entities.ScanTypeDefinition", "ScanTypeDefinition")
                        .WithMany()
                        .HasForeignKey("ScanTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonitoredJob");

                    b.Navigation("ScanTypeDefinition");
                });

            modelBuilder.Entity("Maia.Core.Entities.AiRecommendation", b =>
                {
                    b.Navigation("OperatorActions");
                });

            modelBuilder.Entity("Maia.Core.Entities.ClassificationRule", b =>
                {
                    b.Navigation("MonitoredJobRules");
                });

            modelBuilder.Entity("Maia.Core.Entities.ErrorType", b =>
                {
                    b.Navigation("ClassificationRules");

                    b.Navigation("FixPolicyRules");

                    b.Navigation("JobFailures");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Maia.Core.Entities.FixPolicyRule", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Maia.Core.Entities.JobFailure", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("FixExecutionLogs");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Maia.Core.Entities.JobType", b =>
                {
                    b.Navigation("ClassificationRules");

                    b.Navigation("FixPolicyRules");

                    b.Navigation("JobFailures");

                    b.Navigation("MonitoredJobs");
                });

            modelBuilder.Entity("Maia.Core.Entities.MonitoredJob", b =>
                {
                    b.Navigation("Failures");

                    b.Navigation("JobRules");

                    b.Navigation("Lease");

                    b.Navigation("ScanCheckRules");

                    b.Navigation("ScanSources");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanSource", b =>
                {
                    b.Navigation("ScanCheckRules");
                });

            modelBuilder.Entity("Maia.Core.Entities.ScanTypeDefinition", b =>
                {
                    b.Navigation("MonitoredJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
