-- ============================================================
-- MAIA AI Engine - database schema (tables + indexes only).
-- Generated by Scripts/GenerateSchema. Do not hand-edit.
--
-- Deploy sequence on a fresh server:
--   1. schema-create.sql   (this file)
--   2. seed-metadata.sql
--   3. seed-nsg-events.sql
--
-- The CREATE DATABASE block below is OPTIONAL. Delete it (down to the first
-- CREATE TABLE) if you create [MaiaDB] yourself with custom file settings.
-- NOTE: the application connection string must target this database name.
-- ============================================================

IF DB_ID(N'MaiaDB') IS NULL
    CREATE DATABASE [MaiaDB];
GO

USE [MaiaDB];
GO

CREATE TABLE [ErrorTypes] (
    [ErrorTypeId] int NOT NULL IDENTITY,
    [Code] nvarchar(50) NOT NULL,
    [DisplayName] nvarchar(100) NOT NULL,
    [Description] nvarchar(500) NULL,
    [Severity] nvarchar(20) NOT NULL,
    [IsActive] bit NOT NULL DEFAULT CAST(1 AS bit),
    CONSTRAINT [PK_ErrorTypes] PRIMARY KEY ([ErrorTypeId])
);
GO



CREATE TABLE [JobTypes] (
    [JobTypeId] int NOT NULL IDENTITY,
    [Name] nvarchar(100) NOT NULL,
    [Description] nvarchar(500) NULL,
    [IsActive] bit NOT NULL DEFAULT CAST(1 AS bit),
    CONSTRAINT [PK_JobTypes] PRIMARY KEY ([JobTypeId])
);
GO



CREATE TABLE [Roles] (
    [RoleId] int NOT NULL,
    [Name] nvarchar(50) NOT NULL,
    CONSTRAINT [PK_Roles] PRIMARY KEY ([RoleId])
);
GO



CREATE TABLE [ScanTypes] (
    [ScanTypeId] int NOT NULL IDENTITY,
    [Name] nvarchar(100) NOT NULL,
    [Description] nvarchar(500) NULL,
    [LeaseDurationSeconds] int NOT NULL DEFAULT 300,
    CONSTRAINT [PK_ScanTypes] PRIMARY KEY ([ScanTypeId])
);
GO



CREATE TABLE [ClassificationRules] (
    [RuleId] int NOT NULL IDENTITY,
    [JobTypeId] int NOT NULL,
    [ErrorTypeId] int NOT NULL,
    [Pattern] nvarchar(500) NOT NULL,
    [Confidence] decimal(5,2) NOT NULL,
    [Priority] int NOT NULL,
    [IsActive] bit NOT NULL DEFAULT CAST(1 AS bit),
    [CreatedBy] nvarchar(100) NULL,
    [SuggestedBy] nvarchar(50) NULL,
    [SuggestedFromHash] nvarchar(64) NULL,
    [SuggestedConfidence] decimal(5,2) NULL,
    CONSTRAINT [PK_ClassificationRules] PRIMARY KEY ([RuleId]),
    CONSTRAINT [FK_ClassificationRules_ErrorTypes_ErrorTypeId] FOREIGN KEY ([ErrorTypeId]) REFERENCES [ErrorTypes] ([ErrorTypeId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_ClassificationRules_JobTypes_JobTypeId] FOREIGN KEY ([JobTypeId]) REFERENCES [JobTypes] ([JobTypeId]) ON DELETE NO ACTION
);
GO



CREATE TABLE [MonitoredJobs] (
    [MonitoredJobId] int NOT NULL IDENTITY,
    [Name] nvarchar(200) NOT NULL,
    [DisplayName] nvarchar(300) NULL,
    [JobTypeId] int NOT NULL,
    [PollingIntervalSeconds] int NOT NULL DEFAULT 300,
    [IsActive] bit NOT NULL DEFAULT CAST(1 AS bit),
    [Description] nvarchar(1000) NULL,
    [CreatedAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    CONSTRAINT [PK_MonitoredJobs] PRIMARY KEY ([MonitoredJobId]),
    CONSTRAINT [FK_MonitoredJobs_JobTypes_JobTypeId] FOREIGN KEY ([JobTypeId]) REFERENCES [JobTypes] ([JobTypeId]) ON DELETE NO ACTION
);
GO



CREATE TABLE [Users] (
    [UserId] int NOT NULL IDENTITY,
    [Username] nvarchar(100) NOT NULL,
    [PasswordHash] nvarchar(500) NOT NULL,
    [RoleId] int NOT NULL,
    [IsActive] bit NOT NULL DEFAULT CAST(1 AS bit),
    [MustChangePassword] bit NOT NULL DEFAULT CAST(0 AS bit),
    [CreatedAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    [LastLoginAt] datetime2 NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY ([UserId]),
    CONSTRAINT [FK_Users_Roles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [Roles] ([RoleId]) ON DELETE NO ACTION
);
GO



CREATE TABLE [FixPolicyRules] (
    [RuleId] int NOT NULL IDENTITY,
    [JobTypeId] int NOT NULL,
    [ErrorTypeId] int NOT NULL,
    [MonitoredJobId] int NULL,
    [ActionToApply] nvarchar(300) NOT NULL,
    [FixCategory] nvarchar(50) NOT NULL,
    [IsAutoHealEligible] bit NOT NULL DEFAULT CAST(0 AS bit),
    [Enabled] bit NOT NULL DEFAULT CAST(1 AS bit),
    [CreatedBy] nvarchar(100) NULL,
    [ActionTimestamp] datetime2 NOT NULL DEFAULT (GETDATE()),
    [SuggestedBy] nvarchar(50) NULL,
    [SuggestedFromHash] nvarchar(64) NULL,
    [SuggestedConfidence] decimal(5,2) NULL,
    [ActionType] nvarchar(50) NOT NULL DEFAULT N'Manual',
    [ActionPayload] nvarchar(max) NULL,
    CONSTRAINT [PK_FixPolicyRules] PRIMARY KEY ([RuleId]),
    CONSTRAINT [FK_FixPolicyRules_ErrorTypes_ErrorTypeId] FOREIGN KEY ([ErrorTypeId]) REFERENCES [ErrorTypes] ([ErrorTypeId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_FixPolicyRules_JobTypes_JobTypeId] FOREIGN KEY ([JobTypeId]) REFERENCES [JobTypes] ([JobTypeId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_FixPolicyRules_MonitoredJobs_MonitoredJobId] FOREIGN KEY ([MonitoredJobId]) REFERENCES [MonitoredJobs] ([MonitoredJobId]) ON DELETE NO ACTION
);
GO



CREATE TABLE [MonitoredJobLeases] (
    [MonitoredJobId] int NOT NULL,
    [LeasedBy] nvarchar(200) NULL,
    [LeasedAt] datetime2(3) NULL,
    [LeasedUntil] datetime2(3) NULL,
    [NextEligibleAt] datetime2(3) NOT NULL DEFAULT ('0001-01-01'),
    [LastRunStartedAt] datetime2(3) NULL,
    [LastRunCompletedAt] datetime2(3) NULL,
    [LastRunOutcome] nvarchar(50) NULL,
    [LastRunError] nvarchar(2000) NULL,
    CONSTRAINT [PK_MonitoredJobLeases] PRIMARY KEY ([MonitoredJobId]),
    CONSTRAINT [FK_MonitoredJobLeases_MonitoredJobs_MonitoredJobId] FOREIGN KEY ([MonitoredJobId]) REFERENCES [MonitoredJobs] ([MonitoredJobId]) ON DELETE CASCADE
);
GO



CREATE TABLE [MonitoredJobRules] (
    [JobRuleId] int NOT NULL IDENTITY,
    [MonitoredJobId] int NOT NULL,
    [RuleId] int NOT NULL,
    [IsActive] bit NOT NULL DEFAULT CAST(1 AS bit),
    CONSTRAINT [PK_MonitoredJobRules] PRIMARY KEY ([JobRuleId]),
    CONSTRAINT [FK_MonitoredJobRules_ClassificationRules_RuleId] FOREIGN KEY ([RuleId]) REFERENCES [ClassificationRules] ([RuleId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_MonitoredJobRules_MonitoredJobs_MonitoredJobId] FOREIGN KEY ([MonitoredJobId]) REFERENCES [MonitoredJobs] ([MonitoredJobId]) ON DELETE CASCADE
);
GO



CREATE TABLE [ScanSources] (
    [ScanSourceId] int NOT NULL IDENTITY,
    [MonitoredJobId] int NOT NULL,
    [Name] nvarchar(200) NOT NULL,
    [ScanTypeId] int NOT NULL,
    [LogFolder] nvarchar(500) NULL,
    [SearchPatterns] nvarchar(500) NULL,
    [InputFolder] nvarchar(500) NULL,
    [IncludeSubfolders] bit NOT NULL DEFAULT CAST(0 AS bit),
    [ConnectionName] nvarchar(200) NULL,
    [LogSourceUrl] nvarchar(500) NULL,
    [PollingIntervalSeconds] int NOT NULL DEFAULT 300,
    [IsActive] bit NOT NULL DEFAULT CAST(1 AS bit),
    CONSTRAINT [PK_ScanSources] PRIMARY KEY ([ScanSourceId]),
    CONSTRAINT [FK_ScanSources_MonitoredJobs_MonitoredJobId] FOREIGN KEY ([MonitoredJobId]) REFERENCES [MonitoredJobs] ([MonitoredJobId]) ON DELETE CASCADE,
    CONSTRAINT [FK_ScanSources_ScanTypes_ScanTypeId] FOREIGN KEY ([ScanTypeId]) REFERENCES [ScanTypes] ([ScanTypeId]) ON DELETE NO ACTION
);
GO



CREATE TABLE [UserSessions] (
    [SessionId] int NOT NULL IDENTITY,
    [Token] nvarchar(200) NOT NULL,
    [UserId] int NOT NULL,
    [CreatedAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    [LastActivityAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    CONSTRAINT [PK_UserSessions] PRIMARY KEY ([SessionId]),
    CONSTRAINT [FK_UserSessions_Users_UserId] FOREIGN KEY ([UserId]) REFERENCES [Users] ([UserId]) ON DELETE CASCADE
);
GO



CREATE TABLE [FixPolicyRuleSteps] (
    [StepId] int NOT NULL IDENTITY,
    [RuleId] int NOT NULL,
    [StepOrder] int NOT NULL,
    [ActionType] nvarchar(50) NOT NULL,
    [ActionPayload] nvarchar(max) NOT NULL,
    [Description] nvarchar(200) NULL,
    CONSTRAINT [PK_FixPolicyRuleSteps] PRIMARY KEY ([StepId]),
    CONSTRAINT [FK_FixPolicyRuleSteps_FixPolicyRules_RuleId] FOREIGN KEY ([RuleId]) REFERENCES [FixPolicyRules] ([RuleId]) ON DELETE CASCADE
);
GO



CREATE TABLE [JobFailures] (
    [FailureId] int NOT NULL IDENTITY,
    [JobId] int NOT NULL,
    [JobTypeId] int NOT NULL,
    [ErrorTypeId] int NULL,
    [MonitoredJobId] int NULL,
    [ScanSourceId] int NOT NULL,
    [StepName] nvarchar(200) NULL,
    [SourceId] nvarchar(500) NULL,
    [ReferenceId] nvarchar(500) NULL,
    [ErrorMessage] nvarchar(max) NULL,
    [DetectedAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    [SourceLogPath] nvarchar(200) NOT NULL,
    [SourceFilePath] nvarchar(500) NULL,
    [Status] nvarchar(50) NOT NULL,
    CONSTRAINT [PK_JobFailures] PRIMARY KEY ([FailureId]),
    CONSTRAINT [FK_JobFailures_ErrorTypes_ErrorTypeId] FOREIGN KEY ([ErrorTypeId]) REFERENCES [ErrorTypes] ([ErrorTypeId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_JobFailures_JobTypes_JobTypeId] FOREIGN KEY ([JobTypeId]) REFERENCES [JobTypes] ([JobTypeId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_JobFailures_MonitoredJobs_MonitoredJobId] FOREIGN KEY ([MonitoredJobId]) REFERENCES [MonitoredJobs] ([MonitoredJobId]) ON DELETE SET NULL,
    CONSTRAINT [FK_JobFailures_ScanSources_ScanSourceId] FOREIGN KEY ([ScanSourceId]) REFERENCES [ScanSources] ([ScanSourceId])
);
GO



CREATE TABLE [ScanCheckRules] (
    [CheckRuleId] int NOT NULL IDENTITY,
    [MonitoredJobId] int NOT NULL,
    [ScanSourceId] int NOT NULL,
    [CheckType] nvarchar(50) NOT NULL,
    [SourceTable] nvarchar(max) NULL,
    [TargetField] nvarchar(200) NOT NULL,
    [MinValue] decimal(18,4) NULL,
    [MaxValue] decimal(18,4) NULL,
    [ExpectedValue] nvarchar(500) NULL,
    [WatermarkColumn] nvarchar(200) NULL,
    [SourceIdColumn] nvarchar(200) NULL,
    [ReferenceIdColumn] nvarchar(200) NULL,
    [FilePathColumn] nvarchar(100) NULL,
    [InputPathPattern] nvarchar(500) NULL,
    [ExtractorType] nvarchar(50) NULL,
    [ExtractorLocator] nvarchar(500) NULL,
    [IdentifierLocator] nvarchar(500) NULL,
    [ExtractorPredicateType] nvarchar(50) NULL,
    [ExtractorPredicateValue] nvarchar(500) NULL,
    [Severity] nvarchar(20) NOT NULL,
    [Description] nvarchar(500) NULL,
    [IsActive] bit NOT NULL DEFAULT CAST(1 AS bit),
    CONSTRAINT [PK_ScanCheckRules] PRIMARY KEY ([CheckRuleId]),
    CONSTRAINT [FK_ScanCheckRules_MonitoredJobs_MonitoredJobId] FOREIGN KEY ([MonitoredJobId]) REFERENCES [MonitoredJobs] ([MonitoredJobId]) ON DELETE CASCADE,
    CONSTRAINT [FK_ScanCheckRules_ScanSources_ScanSourceId] FOREIGN KEY ([ScanSourceId]) REFERENCES [ScanSources] ([ScanSourceId])
);
GO



CREATE TABLE [ScanContentWatermarks] (
    [WatermarkId] int NOT NULL IDENTITY,
    [MonitoredJobId] int NOT NULL,
    [ScanSourceId] int NOT NULL,
    [FilePath] nvarchar(500) NOT NULL,
    [LastScannedAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    [LastModifiedAt] datetime2 NOT NULL,
    CONSTRAINT [PK_ScanContentWatermarks] PRIMARY KEY ([WatermarkId]),
    CONSTRAINT [FK_ScanContentWatermarks_MonitoredJobs_MonitoredJobId] FOREIGN KEY ([MonitoredJobId]) REFERENCES [MonitoredJobs] ([MonitoredJobId]) ON DELETE CASCADE,
    CONSTRAINT [FK_ScanContentWatermarks_ScanSources_ScanSourceId] FOREIGN KEY ([ScanSourceId]) REFERENCES [ScanSources] ([ScanSourceId])
);
GO



CREATE TABLE [ScanFileWatermarks] (
    [WatermarkId] int NOT NULL IDENTITY,
    [MonitoredJobId] int NOT NULL,
    [ScanSourceId] int NOT NULL,
    [FilePath] nvarchar(500) NOT NULL,
    [ByteOffset] bigint NOT NULL,
    [LastScannedAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    CONSTRAINT [PK_ScanFileWatermarks] PRIMARY KEY ([WatermarkId]),
    CONSTRAINT [FK_ScanFileWatermarks_MonitoredJobs_MonitoredJobId] FOREIGN KEY ([MonitoredJobId]) REFERENCES [MonitoredJobs] ([MonitoredJobId]) ON DELETE CASCADE,
    CONSTRAINT [FK_ScanFileWatermarks_ScanSources_ScanSourceId] FOREIGN KEY ([ScanSourceId]) REFERENCES [ScanSources] ([ScanSourceId])
);
GO



CREATE TABLE [ScanRunHistory] (
    [ScanRunId] int NOT NULL IDENTITY,
    [MonitoredJobId] int NOT NULL,
    [ScanSourceId] int NOT NULL,
    [LeasedBy] nvarchar(200) NOT NULL,
    [StartedAt] datetime2(3) NOT NULL,
    [CompletedAt] datetime2(3) NOT NULL,
    [DurationMs] int NOT NULL,
    [Outcome] nvarchar(50) NOT NULL,
    [Error] nvarchar(2000) NULL,
    [FailuresDetected] int NOT NULL,
    [Classifications] int NOT NULL,
    [Recommendations] int NOT NULL,
    [IdentifierExtractionFailures] int NOT NULL DEFAULT 0,
    [OversizeFileSkips] int NOT NULL DEFAULT 0,
    [PredicateUnevaluableSkips] int NOT NULL DEFAULT 0,
    CONSTRAINT [PK_ScanRunHistory] PRIMARY KEY ([ScanRunId]),
    CONSTRAINT [FK_ScanRunHistory_MonitoredJobs_MonitoredJobId] FOREIGN KEY ([MonitoredJobId]) REFERENCES [MonitoredJobs] ([MonitoredJobId]) ON DELETE CASCADE,
    CONSTRAINT [FK_ScanRunHistory_ScanSources_ScanSourceId] FOREIGN KEY ([ScanSourceId]) REFERENCES [ScanSources] ([ScanSourceId])
);
GO



CREATE TABLE [AIRecommendations] (
    [RecommendationId] int NOT NULL IDENTITY,
    [FailureId] int NOT NULL,
    [ErrorTypeId] int NOT NULL,
    [SuggestedAction] nvarchar(500) NOT NULL,
    [FixCategory] nvarchar(50) NOT NULL,
    [ConfidenceScore] decimal(5,2) NOT NULL,
    [Explanation] nvarchar(max) NULL,
    [RecommendedAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    [AutoFixAvailable] bit NOT NULL DEFAULT CAST(0 AS bit),
    [OperatorApproved] bit NULL,
    [IsExecuted] bit NOT NULL DEFAULT CAST(0 AS bit),
    [ClaimedBy] nvarchar(200) NULL,
    [ClaimedAt] datetime2 NULL,
    CONSTRAINT [PK_AIRecommendations] PRIMARY KEY ([RecommendationId]),
    CONSTRAINT [FK_AIRecommendations_ErrorTypes_ErrorTypeId] FOREIGN KEY ([ErrorTypeId]) REFERENCES [ErrorTypes] ([ErrorTypeId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_AIRecommendations_JobFailures_FailureId] FOREIGN KEY ([FailureId]) REFERENCES [JobFailures] ([FailureId]) ON DELETE CASCADE
);
GO



CREATE TABLE [AuditLog] (
    [AuditId] int NOT NULL IDENTITY,
    [FailureId] int NULL,
    [EntityType] nvarchar(100) NULL,
    [EntityId] nvarchar(100) NULL,
    [EventType] nvarchar(100) NOT NULL,
    [Actor] nvarchar(100) NOT NULL,
    [Detail] nvarchar(max) NULL,
    [Timestamp] datetime2 NOT NULL DEFAULT (GETDATE()),
    CONSTRAINT [PK_AuditLog] PRIMARY KEY ([AuditId]),
    CONSTRAINT [FK_AuditLog_JobFailures_FailureId] FOREIGN KEY ([FailureId]) REFERENCES [JobFailures] ([FailureId]) ON DELETE CASCADE
);
GO



CREATE TABLE [ScanDbWatermarks] (
    [WatermarkId] int NOT NULL IDENTITY,
    [CheckRuleId] int NOT NULL,
    [WatermarkValue] nvarchar(100) NOT NULL,
    [LastScannedAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    CONSTRAINT [PK_ScanDbWatermarks] PRIMARY KEY ([WatermarkId]),
    CONSTRAINT [FK_ScanDbWatermarks_ScanCheckRules_CheckRuleId] FOREIGN KEY ([CheckRuleId]) REFERENCES [ScanCheckRules] ([CheckRuleId]) ON DELETE CASCADE
);
GO



CREATE TABLE [FixExecutionLog] (
    [FixId] int NOT NULL IDENTITY,
    [FailureId] int NOT NULL,
    [RecommendationId] int NOT NULL,
    [ExecutedAction] nvarchar(300) NOT NULL,
    [TriggerType] nvarchar(50) NOT NULL,
    [ExecutedBy] nvarchar(100) NOT NULL,
    [ExecutedAt] datetime2 NOT NULL DEFAULT (GETDATE()),
    [Success] bit NOT NULL,
    [ResultDetail] nvarchar(max) NULL,
    CONSTRAINT [PK_FixExecutionLog] PRIMARY KEY ([FixId]),
    CONSTRAINT [FK_FixExecutionLog_AIRecommendations_RecommendationId] FOREIGN KEY ([RecommendationId]) REFERENCES [AIRecommendations] ([RecommendationId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_FixExecutionLog_JobFailures_FailureId] FOREIGN KEY ([FailureId]) REFERENCES [JobFailures] ([FailureId]) ON DELETE CASCADE
);
GO



CREATE TABLE [OperatorActions] (
    [ActionId] int NOT NULL IDENTITY,
    [RecommendationId] int NOT NULL,
    [OperatorId] nvarchar(100) NOT NULL,
    [ActionTaken] nvarchar(200) NOT NULL,
    [ActionTimestamp] datetime2 NOT NULL DEFAULT (GETDATE()),
    CONSTRAINT [PK_OperatorActions] PRIMARY KEY ([ActionId]),
    CONSTRAINT [FK_OperatorActions_AIRecommendations_RecommendationId] FOREIGN KEY ([RecommendationId]) REFERENCES [AIRecommendations] ([RecommendationId]) ON DELETE CASCADE
);
GO



CREATE INDEX [IX_AIRecommendations_ClaimEligible] ON [AIRecommendations] ([IsExecuted], [ClaimedAt]) WHERE [IsExecuted] = 0;
GO



CREATE INDEX [IX_AIRecommendations_ErrorTypeId] ON [AIRecommendations] ([ErrorTypeId]);
GO



CREATE INDEX [IX_AIRecommendations_FailureId] ON [AIRecommendations] ([FailureId]);
GO



CREATE INDEX [IX_AuditLog_FailureId] ON [AuditLog] ([FailureId]);
GO



CREATE INDEX [IX_ClassificationRules_ErrorTypeId] ON [ClassificationRules] ([ErrorTypeId]);
GO



CREATE UNIQUE INDEX [UX_ClassificationRules_ActiveKey] ON [ClassificationRules] ([JobTypeId], [Pattern]) WHERE [IsActive] = 1;
GO



CREATE UNIQUE INDEX [IX_ErrorTypes_Code] ON [ErrorTypes] ([Code]);
GO



CREATE INDEX [IX_FixExecutionLog_FailureId] ON [FixExecutionLog] ([FailureId]);
GO



CREATE INDEX [IX_FixExecutionLog_RecommendationId] ON [FixExecutionLog] ([RecommendationId]);
GO



CREATE INDEX [IX_FixPolicyRules_ErrorTypeId] ON [FixPolicyRules] ([ErrorTypeId]);
GO



CREATE UNIQUE INDEX [UX_FixPolicyRules_DefaultActiveKey] ON [FixPolicyRules] ([JobTypeId], [ErrorTypeId]) WHERE [Enabled] = 1 AND [MonitoredJobId] IS NULL;
GO



CREATE UNIQUE INDEX [UX_FixPolicyRules_OverrideActiveKey] ON [FixPolicyRules] ([MonitoredJobId], [ErrorTypeId]) WHERE [Enabled] = 1 AND [MonitoredJobId] IS NOT NULL;
GO



CREATE UNIQUE INDEX [UX_FixPolicyRuleSteps_RuleId_StepOrder] ON [FixPolicyRuleSteps] ([RuleId], [StepOrder]);
GO



CREATE INDEX [IX_JobFailures_ErrorTypeId] ON [JobFailures] ([ErrorTypeId]);
GO



CREATE INDEX [IX_JobFailures_JobTypeId] ON [JobFailures] ([JobTypeId]);
GO



CREATE INDEX [IX_JobFailures_MonitoredJobId] ON [JobFailures] ([MonitoredJobId]);
GO



CREATE INDEX [IX_JobFailures_ScanSourceId] ON [JobFailures] ([ScanSourceId]);
GO



CREATE INDEX [IX_MonitoredJobLeases_Eligible] ON [MonitoredJobLeases] ([NextEligibleAt], [LeasedUntil]);
GO



CREATE UNIQUE INDEX [IX_MonitoredJobRules_MonitoredJobId_RuleId] ON [MonitoredJobRules] ([MonitoredJobId], [RuleId]);
GO



CREATE INDEX [IX_MonitoredJobRules_RuleId] ON [MonitoredJobRules] ([RuleId]);
GO



CREATE INDEX [IX_MonitoredJobs_JobTypeId] ON [MonitoredJobs] ([JobTypeId]);
GO



CREATE UNIQUE INDEX [IX_MonitoredJobs_Name] ON [MonitoredJobs] ([Name]);
GO



CREATE INDEX [IX_OperatorActions_RecommendationId] ON [OperatorActions] ([RecommendationId]);
GO



CREATE UNIQUE INDEX [IX_Roles_Name] ON [Roles] ([Name]);
GO



CREATE INDEX [IX_ScanCheckRules_MonitoredJobId] ON [ScanCheckRules] ([MonitoredJobId]);
GO



CREATE INDEX [IX_ScanCheckRules_ScanSourceId] ON [ScanCheckRules] ([ScanSourceId]);
GO



CREATE UNIQUE INDEX [IX_ScanContentWatermarks_MonitoredJobId_FilePath] ON [ScanContentWatermarks] ([MonitoredJobId], [FilePath]);
GO



CREATE INDEX [IX_ScanContentWatermarks_ScanSourceId] ON [ScanContentWatermarks] ([ScanSourceId]);
GO



CREATE UNIQUE INDEX [IX_ScanDbWatermarks_CheckRuleId] ON [ScanDbWatermarks] ([CheckRuleId]);
GO



CREATE UNIQUE INDEX [IX_ScanFileWatermarks_MonitoredJobId_FilePath] ON [ScanFileWatermarks] ([MonitoredJobId], [FilePath]);
GO



CREATE INDEX [IX_ScanFileWatermarks_ScanSourceId] ON [ScanFileWatermarks] ([ScanSourceId]);
GO



CREATE INDEX [IX_ScanRunHistory_Failures] ON [ScanRunHistory] ([StartedAt] DESC) INCLUDE ([MonitoredJobId], [Outcome], [Error]) WHERE [Outcome] <> 'Success';
GO



CREATE INDEX [IX_ScanRunHistory_Job_StartedAt] ON [ScanRunHistory] ([MonitoredJobId], [StartedAt] DESC) INCLUDE ([CompletedAt], [DurationMs], [Outcome], [FailuresDetected], [Classifications], [Recommendations]);
GO



CREATE INDEX [IX_ScanRunHistory_Source_StartedAt] ON [ScanRunHistory] ([ScanSourceId], [StartedAt] DESC);
GO



CREATE INDEX [IX_ScanSources_MonitoredJobId] ON [ScanSources] ([MonitoredJobId]);
GO



CREATE INDEX [IX_ScanSources_ScanTypeId] ON [ScanSources] ([ScanTypeId]);
GO



CREATE INDEX [IX_Users_RoleId] ON [Users] ([RoleId]);
GO



CREATE UNIQUE INDEX [IX_Users_Username] ON [Users] ([Username]);
GO



CREATE UNIQUE INDEX [IX_UserSessions_Token] ON [UserSessions] ([Token]);
GO



CREATE INDEX [IX_UserSessions_UserId] ON [UserSessions] ([UserId]);
GO
