using Maia.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;

// Run from project root: dotnet run --project Scripts/GenerateSchema
// Output: Scripts/schema-create.sql
//
// Emits a PURE schema script: CREATE TABLE + CREATE INDEX only.
// EF's GenerateCreateScript() also bakes in every HasData() seed row as an
// INSERT / SET IDENTITY_INSERT batch — those are data, not schema, and belong
// in seed-metadata.sql. We strip them out here so the schema file stays clean.
var outPath = Path.Combine(Directory.GetCurrentDirectory(), "Scripts", "schema-create.sql");

var opts = new DbContextOptionsBuilder<MaiaDbContext>()
    .UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=AIEngineDb;Trusted_Connection=True;TrustServerCertificate=True;")
    .Options;

using var ctx = new MaiaDbContext(opts);
var raw = ctx.Database.GenerateCreateScript();

// Split into GO-delimited batches; drop any batch that is seed data
// (contains INSERT INTO or SET IDENTITY_INSERT). Keep CREATE TABLE / CREATE INDEX.
var lines = raw.Replace("\r\n", "\n").Split('\n');
var batch = new List<string>();
var kept = new List<string>();

void Flush()
{
    if (batch.Count == 0) return;
    var text = string.Join("\n", batch);
    var isSeed = text.Contains("INSERT INTO", StringComparison.OrdinalIgnoreCase)
              || text.Contains("SET IDENTITY_INSERT", StringComparison.OrdinalIgnoreCase);
    if (!isSeed && text.Trim().Length > 0)
    {
        kept.AddRange(batch);
        kept.Add("GO");
        kept.Add("");
    }
    batch.Clear();
}

foreach (var line in lines)
{
    if (line.Trim() == "GO")
    {
        Flush();
        continue;
    }
    batch.Add(line);
}
Flush();

// Collapse trailing blank lines.
var body = string.Join("\n", kept).TrimEnd() + "\n";

// Optional, idempotent database-creation header. Safe to re-run; a DBA who wants
// custom file placement / collation / recovery model can delete this block and
// create [MaiaDB] manually before running the rest of the script.
const string dbName = "MaiaDB";
var header =
$@"-- ============================================================
-- MAIA AI Engine - database schema (tables + indexes only).
-- Generated by Scripts/GenerateSchema. Do not hand-edit.
--
-- Deploy sequence on a fresh server:
--   1. schema-create.sql   (this file)
--   2. seed-metadata.sql
--   3. seed-nsg-events.sql
--
-- The CREATE DATABASE block below is OPTIONAL. Delete it (down to the first
-- CREATE TABLE) if you create [{dbName}] yourself with custom file settings.
-- NOTE: the application connection string must target this database name.
-- ============================================================

IF DB_ID(N'{dbName}') IS NULL
    CREATE DATABASE [{dbName}];
GO

USE [{dbName}];
GO

";

var script = header + body;

File.WriteAllText(outPath, script, new System.Text.UTF8Encoding(false));
Console.WriteLine($"Written {script.Split('\n').Length} lines (schema only, seed data stripped) to {outPath}");
